name: Generate RSS feed and upload to webpage

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 12 * * 1-5'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
      - run: pip install -r requirements.txt
      - run: |
          mkdir feeds
          python single.py --folder feeds --programma https://www.raiplaysound.it/programmi/radio3scienza
          chmod 644 feeds/*
      - uses: actions/upload-pages-artifact@v3
        with:
          path: "feeds/"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}  

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
